### ISSUE TITLE
test

### ISSUE THREAD

**Issue by JiangWeixian** [JiangWeixian/actions-article-helper#1]
My blog site is built on top of GitHub issues. When I create or edit my issue on GitHub, `next.js` ISR will recreate my blog site in the background. Additionally, ChatGPT is an excellent AI assistant tool that can be used for many purposes, such as a search engine and language translator. As a non-native English speaker, I plan to add ChatGPT to my article writing workflow this weekend to check my articles' grammar like a native English speaker.

## TL;DR

If you write articles on GitHub issues like me, you can use the https://github.com/JiangWeixian/actions-article-helper action in your blog repository.

```yaml
name: "article helper"
on:
  issues:
    types:
      - "opened"
      - "edited"

jobs:
  debug:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: setup node.js
      uses: actions/setup-node@v2
      with:
        node-version: 16
    - name: article helper
      uses: jiangweixian/actions-article-helper@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
```

DEMO:

![image](https://user-images.githubusercontent.com/6839576/218319909-bc601e3d-942c-4c05-b49a-4fbab2057b23.png)

## ChatGPT Open API

Lucky, ChatGPT provide open-api. First you should create `API_KEY` on `OpenAI` platform https://platform.openai.com/account/api-keys.

```ts
import { ChatGPTAPI } from 'chatgpt'

export const createChatGPTAPI = (apiKey: string) => {
  return new ChatGPTAPI({
    apiKey, // add you open-ai API_KEY here
  })
}
```

> package `chatgpt` is a request client wrapper the basic `open-ai` endpoint.

Now, you can send you article content(from issue body) to `ChatGPT`, let `ChatGPT` to check grammar and rewrite it.

```js
const client = createChatGPTAPI(apiKey)
client.sendMessage(content)
```

By default, you can't send article content like `Hey, chatgpt help me check {{ content }} grammar`. Maybe it will not work as you expect.

To make `ChatGPT` act as native English speaker, you need **prompts**. **prompts** like language(like `JavaScript or Rust`) that `ChatGPT` will understand better.

Theres are lots of prompts you can play with from https://github.com/f/awesome-chatgpt-prompts.

In order to make `ChatGPT` work as English native. Article content will send with the follow prompts, just replace `"istanbulu cok seviyom burada olmak cok guzel"` with real article content.

> I want you to act as an English translator, spelling corrector and improver. I will speak to you in any language and you will detect the language, translate it and answer in the corrected and improved version of my text, in English. I want you to replace my simplified A0-level words and sentences with more beautiful and elegant, upper level English words and sentences. Keep the meaning same, but make them more literary. I want you to only reply the correction, the improvements and nothing else, do not write explanations. My markdown format article is "istanbulu cok seviyom burada olmak cok guzel" 

```js
const client = createChatGPTAPI(apiKey)
const result = await chatgptApi.sendMessage(article, {
  stream: true,
  // response original markdown format
  promptPrefix: 'Respond markdown format.<|im_end|>\n',
})
```

The main(hardest) part is complete, now we go futurter, and make it interaction with github actions.

## Github Actions

First, get issue content

```ts
const issue = await octokit.rest.issues.get(params)
```

Then create comment under issue

```ts
await octokit.rest.issues.createComment({
  ...,
  body: result.text, // result is ChatGPT respsonse result.
})
```

That works great, but not perfect. Before issue publish, issue body will edit mutiple times. I don't wan't create too much comments, I need to find previous comment, and update it.

```ts
const comments = await octokit.rest.issues.listComments(params)
// find comments by bot<github_actioins> start with `<!--article-helper-->`
const comment = findComment(comments.data)
debug('find comment %o', comment)
if (comment) {
  await octokit.rest.issues.updateComment({
    owner,
    repo,
    comment_id: comment?.id,
    body: withLeadPrefix(`${result.text} ${Date.now()}`),
  })
} else {
  // create comment
}
```
